
const begin = {"Title":"Begin Again","Year":"2013","Rated":"R","Released":"11 Jul 2014","Runtime":"104 min","Genre":"Comedy, Drama, Music","Director":"John Carney","Writer":"John Carney","Actors":"Keira Knightley, Mark Ruffalo, Adam Levine","Plot":"A chance encounter between a down-and-out music-business executive and a young singer-songwriter, new to Manhattan, turns into a promising collaboration between the two talents.","Language":"English","Country":"United States","Awards":"Nominated for 1 Oscar. 5 wins & 18 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BNjAxMTI4MTgzMV5BMl5BanBnXkFtZTgwOTAwODEwMjE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.4/10"},{"Source":"Rotten Tomatoes","Value":"83%"},{"Source":"Metacritic","Value":"62/100"}],"Metascore":"62","imdbRating":"7.4","imdbVotes":"160,616","imdbID":"tt1980929","Type":"movie","DVD":"28 Oct 2014","BoxOffice":"$16,170,632","Production":"N/A","Website":"N/A","Response":"True"};


const casablanca = {"Title":"Casablanca","Year":"1942","Rated":"PG","Released":"23 Jan 1943","Runtime":"102 min","Genre":"Drama, Romance, War","Director":"Michael Curtiz","Writer":"Julius J. Epstein, Philip G. Epstein, Howard Koch","Actors":"Humphrey Bogart, Ingrid Bergman, Paul Henreid","Plot":"A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco.","Language":"English, French, German, Italian","Country":"United States","Awards":"Won 3 Oscars. 13 wins & 9 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"99%"},{"Source":"Metacritic","Value":"100/100"}],"Metascore":"100","imdbRating":"8.5","imdbVotes":"581,341","imdbID":"tt0034583","Type":"movie","DVD":"17 Nov 1998","BoxOffice":"$4,219,709","Production":"N/A","Website":"N/A","Response":"True"};

const tesis = {"Title":"Tesis","Year":"1996","Rated":"R","Released":"12 Apr 1996","Runtime":"125 min","Genre":"Crime, Horror, Mystery","Director":"Alejandro Amenábar","Writer":"Alejandro Amenábar, Mateo Gil","Actors":"Ana Torrent, Fele Martínez, Eduardo Noriega","Plot":"While doing a thesis about violence, Ángela finds a snuff video where a girl is tortured until death. Soon she discovers that the girl was a former student in her faculty...","Language":"Spanish","Country":"Spain","Awards":"15 wins & 6 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BYTNjOGMzOTgtYWVmMi00ZWYzLWI4ZDItZjRhMjU3MzBhY2UwXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.4/10"},{"Source":"Rotten Tomatoes","Value":"83%"}],"Metascore":"N/A","imdbRating":"7.4","imdbVotes":"40,399","imdbID":"tt0117883","Type":"movie","DVD":"08 Feb 2011","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"};

const avatar = {"Title":"Avatar","Year":"2009","Rated":"PG-13","Released":"18 Dec 2009","Runtime":"162 min","Genre":"Action, Adventure, Fantasy","Director":"James Cameron","Writer":"James Cameron","Actors":"Sam Worthington, Zoe Saldana, Sigourney Weaver","Plot":"A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.","Language":"English, Spanish","Country":"United States","Awards":"Won 3 Oscars. 89 wins & 131 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.9/10"},{"Source":"Rotten Tomatoes","Value":"82%"},{"Source":"Metacritic","Value":"83/100"}],"Metascore":"83","imdbRating":"7.9","imdbVotes":"1,338,789","imdbID":"tt0499549","Type":"movie","DVD":"22 Apr 2010","BoxOffice":"$785,221,649","Production":"N/A","Website":"N/A","Response":"True"};

const apartamento = {"Title":"The Apartment","Year":"1960","Rated":"Approved","Released":"29 Jun 1960","Runtime":"125 min","Genre":"Comedy, Drama, Romance","Director":"Billy Wilder","Writer":"Billy Wilder, I.A.L. Diamond","Actors":"Jack Lemmon, Shirley MacLaine, Fred MacMurray","Plot":"A Manhattan insurance clerk tries to rise in his company by letting its executives use his apartment for trysts, but complications and a romance of his own ensue.","Language":"English","Country":"United States","Awards":"Won 5 Oscars. 24 wins & 8 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BNzkwODFjNzItMmMwNi00MTU5LWE2MzktM2M4ZDczZGM1MmViXkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.3/10"},{"Source":"Rotten Tomatoes","Value":"93%"},{"Source":"Metacritic","Value":"94/100"}],"Metascore":"94","imdbRating":"8.3","imdbVotes":"186,043","imdbID":"tt0053604","Type":"movie","DVD":"04 Mar 2008","BoxOffice":"$18,600,000","Production":"N/A","Website":"N/A","Response":"True"};

const faldas = {"Title":"Some Like It Hot","Year":"1959","Rated":"Passed","Released":"19 Mar 1959","Runtime":"121 min","Genre":"Comedy, Music, Romance","Director":"Billy Wilder","Writer":"Billy Wilder, I.A.L. Diamond, Robert Thoeren","Actors":"Marilyn Monroe, Tony Curtis, Jack Lemmon","Plot":"After two male musicians witness a mob hit, they flee the state in an all-female band disguised as women, but further complications set in.","Language":"English","Country":"United States","Awards":"Won 1 Oscar. 15 wins & 15 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BNzAyOGIxYjAtMGY2NC00ZTgyLWIwMWEtYzY0OWQ4NDFjOTc5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.2/10"},{"Source":"Rotten Tomatoes","Value":"94%"},{"Source":"Metacritic","Value":"98/100"}],"Metascore":"98","imdbRating":"8.2","imdbVotes":"272,455","imdbID":"tt0053291","Type":"movie","DVD":"18 Jul 2006","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"}

const guerraGalax = {"Title":"Star Wars: Episode IV - A New Hope","Year":"1977","Rated":"PG","Released":"25 May 1977","Runtime":"121 min","Genre":"Action, Adventure, Fantasy","Director":"George Lucas","Writer":"George Lucas","Actors":"Mark Hamill, Harrison Ford, Carrie Fisher","Plot":"Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth ...","Language":"English","Country":"United States","Awards":"Won 6 Oscars. 65 wins & 31 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.6/10"},{"Source":"Rotten Tomatoes","Value":"93%"},{"Source":"Metacritic","Value":"90/100"}],"Metascore":"90","imdbRating":"8.6","imdbVotes":"1,388,289","imdbID":"tt0076759","Type":"movie","DVD":"06 Dec 2005","BoxOffice":"$460,998,507","Production":"N/A","Website":"N/A","Response":"True"}

const regreso = {"Title":"Back to the Future","Year":"1985","Rated":"PG","Released":"03 Jul 1985","Runtime":"116 min","Genre":"Adventure, Comedy, Sci-Fi","Director":"Robert Zemeckis","Writer":"Robert Zemeckis, Bob Gale","Actors":"Michael J. Fox, Christopher Lloyd, Lea Thompson","Plot":"Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.","Language":"English","Country":"United States","Awards":"Won 1 Oscar. 23 wins & 25 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"97%"},{"Source":"Metacritic","Value":"87/100"}],"Metascore":"87","imdbRating":"8.5","imdbVotes":"1,233,438","imdbID":"tt0088763","Type":"movie","DVD":"17 Aug 2010","BoxOffice":"$212,836,762","Production":"N/A","Website":"N/A","Response":"True"}

const twoMuch = {"Title":"Two Much","Year":"1995","Rated":"PG-13","Released":"15 Mar 1996","Runtime":"118 min","Genre":"Comedy, Romance","Director":"Fernando Trueba","Writer":"Donald E. Westlake, Fernando Trueba, David Trueba","Actors":"Antonio Banderas, Melanie Griffith, Daryl Hannah","Plot":"A young gallerist is in love with two sisters at the same time. In order to solve the problem he decides to invent his own twin-brother.","Language":"English","Country":"Spain, United States","Awards":"5 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BODI2YmUyNDAtMjAyMy00ZjEzLWExMTktZWUyYjMxYWFlODEyXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"5.4/10"},{"Source":"Rotten Tomatoes","Value":"14%"}],"Metascore":"N/A","imdbRating":"5.4","imdbVotes":"5,819","imdbID":"tt0118001","Type":"movie","DVD":"08 Apr 2003","BoxOffice":"$1,141,556","Production":"N/A","Website":"N/A","Response":"True"}

const vivir = {"Title":"Living Is Easy with Eyes Closed","Year":"2013","Rated":"Not Rated","Released":"31 Oct 2013","Runtime":"108 min","Genre":"Comedy, Drama","Director":"David Trueba","Writer":"David Trueba","Actors":"Javier Cámara, Natalia de Molina, Francesc Colomer","Plot":"In Spain in 1966, an English teacher picks up two hitchhikers on his quest to meet John Lennon.","Language":"Spanish, English","Country":"Spain","Awards":"19 wins & 18 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BNTk4NjYzMjUzM15BMl5BanBnXkFtZTgwNTYwMDcwMjE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.0/10"},{"Source":"Rotten Tomatoes","Value":"94%"}],"Metascore":"N/A","imdbRating":"7.0","imdbVotes":"6,425","imdbID":"tt2896036","Type":"movie","DVD":"21 Apr 2015","BoxOffice":"$11,600","Production":"N/A","Website":"N/A","Response":"True"}

const sobrevivire = {"Title":"I Will Survive","Year":"1999","Rated":"N/A","Released":"19 Nov 1999","Runtime":"102 min","Genre":"Comedy, Drama, Romance","Director":"Alfonso Albacete, David Menkes","Writer":"Alfonso Albacete, Lucía Etxebarría, David Menkes","Actors":"Emma Suárez, Juan Diego Botto, Mirta Ibarra","Plot":"Marga is having a streak of bad luck. She tries to regain her self-confidence through her friendship with Rosa, but love interests again create conflict. While developing a relationship with a handsome gay sculptor 10 years her ju...","Language":"Spanish","Country":"Spain","Awards":"1 win & 1 nomination","Poster":"https://m.media-amazon.com/images/M/MV5BMmE2ODQ5MDAtMWZhZC00MmZkLThlODItN2E3M2U4ODBmYmNiXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.2/10"},{"Source":"Rotten Tomatoes","Value":"43%"},{"Source":"Metacritic","Value":"53/100"}],"Metascore":"53","imdbRating":"6.2","imdbVotes":"840","imdbID":"tt0217811","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"}

const hortelano = {"Title":"The Dog in the Manger","Year":"1996","Rated":"N/A","Released":"25 Oct 1996","Runtime":"119 min","Genre":"Comedy, Romance","Director":"Pilar Miró","Writer":"Félix Lope de Vega, Pilar Miró, Rafael Pérez Sierra","Actors":"Emma Suárez, Carmelo Gómez, Fernando Conde","Plot":"Having taken a fancy to her secretary, Teodoro, spunky young beauty Countess Diana of Belflor is alarmed to learn of his engagement to one of her maids, Marcela. She intervenes to separate them by steering Marcela's affections to ...","Language":"Spanish","Country":"Spain, Portugal","Awards":"13 wins & 6 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BOTk5MTQ3OWEtZWM0YS00MzdiLTliZGEtOGE0MTJjM2QyNDg3XkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.8/10"}],"Metascore":"N/A","imdbRating":"6.8","imdbVotes":"1,029","imdbID":"tt0114115","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"}

const nombre = {"Title":"Tu nombre envenena mis sueños","Year":"1996","Rated":"N/A","Released":"22 Sep 1996","Runtime":"118 min","Genre":"Drama, Romance, Thriller","Director":"Pilar Miró","Writer":"Ricardo Franco, Joaquín Leguina, Pilar Miró","Actors":"Carmelo Gómez, Emma Suárez, Ángel de Andrés López","Plot":"The investigation of an apparent suicide in post-war Spain leads Inspector Barciela to discover a story of revenge for the hatred and grudges of the past.","Language":"Spanish","Country":"Spain","Awards":"3 wins & 1 nomination","Poster":"https://m.media-amazon.com/images/M/MV5BZmY2OWIwMGEtYTgyNy00NmI4LWIxYjktZjBmOGY2N2FiODIwXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.2/10"}],"Metascore":"N/A","imdbRating":"6.2","imdbVotes":"212","imdbID":"tt0117985","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"}

const diasFutbol = {"Title":"Días de fútbol","Year":"2003","Rated":"N/A","Released":"19 Sep 2003","Runtime":"113 min","Genre":"Adventure, Comedy, Sport","Director":"David Serrano","Writer":"Mischa Alexander, David Serrano, Jean van de Velde","Actors":"Alberto San Juan, Ernesto Alterio, Natalia Verbeke","Plot":"A group of 30-year-old friends tries to change their sad existence by setting up a football team like when they were young to see if they finally win something in their lives.","Language":"Spanish, English","Country":"Spain","Awards":"4 wins & 10 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BNTQ1NThmM2YtOWNjOS00YzM2LThmODYtOGU4YjFmM2E1OGQyXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.2/10"}],"Metascore":"N/A","imdbRating":"6.2","imdbVotes":"2,914","imdbID":"tt0377834","Type":"movie","DVD":"06 Sep 2005","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"}

const tiemposModernos = {"Title":"Modern Times","Year":"1936","Rated":"G","Released":"25 Feb 1936","Runtime":"87 min","Genre":"Comedy, Drama, Romance","Director":"Charles Chaplin","Writer":"Charles Chaplin","Actors":"Charles Chaplin, Paulette Goddard, Henry Bergman","Plot":"The Tramp struggles to live in modern industrial society with the help of a young homeless woman.","Language":"English","Country":"United States","Awards":"4 wins & 1 nomination","Poster":"https://m.media-amazon.com/images/M/MV5BYjJiZjMzYzktNjU0NS00OTkxLWEwYzItYzdhYWJjN2QzMTRlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"98%"},{"Source":"Metacritic","Value":"96/100"}],"Metascore":"96","imdbRating":"8.5","imdbVotes":"247,652","imdbID":"tt0027977","Type":"movie","DVD":"16 Nov 2010","BoxOffice":"$163,577","Production":"N/A","Website":"N/A","Response":"True"}

const pulp = {"Title":"Pulp Fiction","Year":"1994","Rated":"R","Released":"14 Oct 1994","Runtime":"154 min","Genre":"Crime, Drama","Director":"Quentin Tarantino","Writer":"Quentin Tarantino, Roger Avary","Actors":"John Travolta, Uma Thurman, Samuel L. Jackson","Plot":"The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.","Language":"English, Spanish, French","Country":"United States","Awards":"Won 1 Oscar. 70 wins & 75 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.9/10"},{"Source":"Rotten Tomatoes","Value":"92%"},{"Source":"Metacritic","Value":"95/100"}],"Metascore":"95","imdbRating":"8.9","imdbVotes":"2,101,116","imdbID":"tt0110912","Type":"movie","DVD":"20 Aug 2002","BoxOffice":"$107,928,762","Production":"N/A","Website":"N/A","Response":"True"}

const vidaBella = {"Title":"Life Is Beautiful","Year":"1997","Rated":"PG-13","Released":"20 Dec 1997","Runtime":"116 min","Genre":"Comedy, Drama, Romance","Director":"Roberto Benigni","Writer":"Vincenzo Cerami, Roberto Benigni","Actors":"Roberto Benigni, Nicoletta Braschi, Giorgio Cantarini","Plot":"When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor and imagination to protect his son from the dangers around their camp.","Language":"Italian, German, English","Country":"Italy","Awards":"Won 3 Oscars. 72 wins & 52 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BYmJmM2Q4NmMtYThmNC00ZjRlLWEyZmItZTIwOTBlZDQ3NTQ1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.6/10"},{"Source":"Rotten Tomatoes","Value":"80%"},{"Source":"Metacritic","Value":"59/100"}],"Metascore":"59","imdbRating":"8.6","imdbVotes":"708,111","imdbID":"tt0118799","Type":"movie","DVD":"09 Nov 1999","BoxOffice":"$57,563,264","Production":"N/A","Website":"N/A","Response":"True"}

const sinPerdon = {"Title":"Unforgiven","Year":"1992","Rated":"R","Released":"07 Aug 1992","Runtime":"130 min","Genre":"Drama, Western","Director":"Clint Eastwood","Writer":"David Webb Peoples","Actors":"Clint Eastwood, Gene Hackman, Morgan Freeman","Plot":"Retired Old West gunslinger William Munny reluctantly takes on one last job, with the help of his old partner Ned Logan and a young man, The \"Schofield Kid.\"","Language":"English","Country":"United States","Awards":"Won 4 Oscars. 50 wins & 47 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BODM3YWY4NmQtN2Y3Ni00OTg0LWFhZGQtZWE3ZWY4MTJlOWU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.2/10"},{"Source":"Rotten Tomatoes","Value":"96%"},{"Source":"Metacritic","Value":"85/100"}],"Metascore":"85","imdbRating":"8.2","imdbVotes":"419,454","imdbID":"tt0105695","Type":"movie","DVD":"30 Oct 2001","BoxOffice":"$101,167,799","Production":"N/A","Website":"N/A","Response":"True"}

const silencio = {"Title":"The Silence of the Lambs","Year":"1991","Rated":"R","Released":"14 Feb 1991","Runtime":"118 min","Genre":"Crime, Drama, Thriller","Director":"Jonathan Demme","Writer":"Thomas Harris, Ted Tally","Actors":"Jodie Foster, Anthony Hopkins, Lawrence A. Bonney","Plot":"A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.","Language":"English, Latin","Country":"United States","Awards":"Won 5 Oscars. 70 wins & 51 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.6/10"},{"Source":"Rotten Tomatoes","Value":"95%"},{"Source":"Metacritic","Value":"86/100"}],"Metascore":"86","imdbRating":"8.6","imdbVotes":"1,462,389","imdbID":"tt0102926","Type":"movie","DVD":"21 Aug 2001","BoxOffice":"$130,742,922","Production":"N/A","Website":"N/A","Response":"True"}

const blade = {"Title":"Blade Runner","Year":"1982","Rated":"R","Released":"25 Jun 1982","Runtime":"117 min","Genre":"Action, Drama, Sci-Fi","Director":"Ridley Scott","Writer":"Hampton Fancher, David Webb Peoples, Philip K. Dick","Actors":"Harrison Ford, Rutger Hauer, Sean Young","Plot":"A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth to find their creator.","Language":"English, German, Cantonese, Japanese, Hungarian, Arabic, Korean","Country":"United States","Awards":"Nominated for 2 Oscars. 13 wins & 19 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BNzQzMzJhZTEtOWM4NS00MTdhLTg0YjgtMjM4MDRkZjUwZDBlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.1/10"},{"Source":"Rotten Tomatoes","Value":"89%"},{"Source":"Metacritic","Value":"84/100"}],"Metascore":"84","imdbRating":"8.1","imdbVotes":"785,273","imdbID":"tt0083658","Type":"movie","DVD":"30 Oct 2001","BoxOffice":"$32,914,489","Production":"N/A","Website":"N/A","Response":"True"}

const roqueiii = {"Title":"Yo hice a Roque III","Year":"1980","Rated":"G","Released":"19 Sep 1980","Runtime":"80 min","Genre":"Comedy","Director":"Mariano Ozores","Writer":"Mariano Ozores","Actors":"Fernando Esteso, Andrés Pajares, Antonio Ozores","Plot":"Federico provides accommodation in his house for his friend Roque who is unemployed and becomes annoying. To get rid of him, Fernando tries to make Roque a boxing champion who will be able to challenge the current national boxing ...","Language":"Spanish","Country":"Spain","Awards":"N/A","Poster":"https://m.media-amazon.com/images/M/MV5BNmU1Y2UxZjItNDcwZi00OGI3LTgwNjQtYmFmY2I4MGExZjgyXkEyXkFqcGdeQXVyMTY5MDE5NA@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"5.5/10"}],"Metascore":"N/A","imdbRating":"5.5","imdbVotes":"432","imdbID":"tt0081790","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"}

const amanece = {"Title":"Amanece, que no es poco","Year":"1989","Rated":"N/A","Released":"13 Jan 1989","Runtime":"110 min","Genre":"Comedy, Fantasy","Director":"José Luis Cuerda","Writer":"José Luis Cuerda","Actors":"José Sazatornil, Carmen de Lirio, Francisco Martínez","Plot":"A village and the crazy situations encountered by its citizens.","Language":"Spanish, French","Country":"Spain","Awards":"3 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BMzJhNzQ0YzQtZjIwYi00NzMwLTgwNjAtMmJhYzFiODBmYWQ1XkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.4/10"}],"Metascore":"N/A","imdbRating":"7.4","imdbVotes":"4,002","imdbID":"tt0094641","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"}

const terminator = {"Title":"The Terminator","Year":"1984","Rated":"R","Released":"26 Oct 1984","Runtime":"107 min","Genre":"Action, Sci-Fi","Director":"James Cameron","Writer":"James Cameron, Gale Anne Hurd, William Wisher","Actors":"Arnold Schwarzenegger, Linda Hamilton, Michael Biehn","Plot":"A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg killing machine, sent from the same year, which has been programmed to execute a young woman whose unborn son is the key to humanity's future salvat...","Language":"English, Spanish","Country":"United Kingdom, United States","Awards":"8 wins & 6 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BYTViNzMxZjEtZGEwNy00MDNiLWIzNGQtZDY2MjQ1OWViZjFmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.1/10"},{"Source":"Rotten Tomatoes","Value":"100%"},{"Source":"Metacritic","Value":"84/100"}],"Metascore":"84","imdbRating":"8.1","imdbVotes":"882,688","imdbID":"tt0088247","Type":"movie","DVD":"02 Oct 2001","BoxOffice":"$38,371,200","Production":"N/A","Website":"N/A","Response":"True"}

const inter = {"Title":"Interstellar","Year":"2014","Rated":"PG-13","Released":"07 Nov 2014","Runtime":"169 min","Genre":"Adventure, Drama, Sci-Fi","Director":"Christopher Nolan","Writer":"Jonathan Nolan, Christopher Nolan","Actors":"Matthew McConaughey, Anne Hathaway, Jessica Chastain","Plot":"A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.","Language":"English","Country":"United States, United Kingdom, Canada","Awards":"Won 1 Oscar. 44 wins & 148 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.6/10"},{"Source":"Rotten Tomatoes","Value":"73%"},{"Source":"Metacritic","Value":"74/100"}],"Metascore":"74","imdbRating":"8.6","imdbVotes":"1,898,118","imdbID":"tt0816692","Type":"movie","DVD":"31 Mar 2015","BoxOffice":"$188,020,017","Production":"N/A","Website":"N/A","Response":"True"}

const laJungla = {"Title":"Die Hard","Year":"1988","Rated":"R","Released":"20 Jul 1988","Runtime":"132 min","Genre":"Action, Thriller","Director":"John McTiernan","Writer":"Roderick Thorp, Jeb Stuart, Steven E. de Souza","Actors":"Bruce Willis, Alan Rickman, Bonnie Bedelia","Plot":"A New York City police officer tries to save his estranged wife and several others taken hostage by terrorists during a Christmas party at the Nakatomi Plaza in Los Angeles.","Language":"English, German, Italian, Japanese","Country":"United States","Awards":"Nominated for 4 Oscars. 8 wins & 6 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BZjRlNDUxZjAtOGQ4OC00OTNlLTgxNmQtYTBmMDgwZmNmNjkxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.2/10"},{"Source":"Rotten Tomatoes","Value":"94%"},{"Source":"Metacritic","Value":"72/100"}],"Metascore":"72","imdbRating":"8.2","imdbVotes":"899,232","imdbID":"tt0095016","Type":"movie","DVD":"28 Dec 1999","BoxOffice":"$83,844,093","Production":"N/A","Website":"N/A","Response":"True"}

const diaBestia = {"Title":"The Day of the Beast","Year":"1995","Rated":"R","Released":"23 Dec 1998","Runtime":"99 min","Genre":"Action, Comedy, Crime","Director":"Álex de la Iglesia","Writer":"Jorge Guerricaechevarría, Álex de la Iglesia","Actors":"Álex Angulo, Armando De Razza, Santiago Segura","Plot":"Bent on committing as many sins as possible to avert the birth of the beast, a Catholic priest teams up with a Black Metal aficionado and an Italian connoisseur of the occult. Now, he must become an unrelenting sinner. Is there st...","Language":"Spanish, Italian","Country":"Spain, Italy","Awards":"16 wins & 14 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BZWRhMWI2NWUtMTQxNC00MzNmLTk4NWEtMDc3ZDBjNjdkODhkXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.3/10"},{"Source":"Rotten Tomatoes","Value":"77%"}],"Metascore":"N/A","imdbRating":"7.3","imdbVotes":"22,554","imdbID":"tt0112922","Type":"movie","DVD":"21 Nov 2020","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"}

const odisea = {"Title":"2001: A Space Odyssey","Year":"1968","Rated":"G","Released":"24 Jun 1970","Runtime":"149 min","Genre":"Adventure, Sci-Fi","Director":"Stanley Kubrick","Writer":"Stanley Kubrick, Arthur C. Clarke","Actors":"Keir Dullea, Gary Lockwood, William Sylvester","Plot":"After uncovering a mysterious artifact buried beneath the Lunar surface, a spacecraft is sent to Jupiter to find its origins - a spacecraft manned by two men and the supercomputer H.A.L. 9000.","Language":"English, Russian, French","Country":"United Kingdom, United States","Awards":"Won 1 Oscar. 17 wins & 12 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMmNlYzRiNDctZWNhMi00MzI4LThkZTctMTUzMmZkMmFmNThmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.3/10"},{"Source":"Rotten Tomatoes","Value":"92%"},{"Source":"Metacritic","Value":"84/100"}],"Metascore":"84","imdbRating":"8.3","imdbVotes":"683,029","imdbID":"tt0062622","Type":"movie","DVD":"23 Oct 2007","BoxOffice":"$60,481,243","Production":"N/A","Website":"N/A","Response":"True"}

const brave = {"Title":"Braveheart","Year":"1995","Rated":"R","Released":"24 May 1995","Runtime":"178 min","Genre":"Biography, Drama, History","Director":"Mel Gibson","Writer":"Randall Wallace","Actors":"Mel Gibson, Sophie Marceau, Patrick McGoohan","Plot":"Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.","Language":"English, French, Latin, Gaelic, Italian","Country":"United States","Awards":"Won 5 Oscars. 33 wins & 34 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMzkzMmU0YTYtOWM3My00YzBmLWI0YzctOGYyNTkwMWE5MTJkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.4/10"},{"Source":"Rotten Tomatoes","Value":"75%"},{"Source":"Metacritic","Value":"68/100"}],"Metascore":"68","imdbRating":"8.4","imdbVotes":"1,053,034","imdbID":"tt0112573","Type":"movie","DVD":"19 Sep 2006","BoxOffice":"$75,609,945","Production":"N/A","Website":"N/A","Response":"True"}

const joker = {"Title":"Joker","Year":"2019","Rated":"R","Released":"04 Oct 2019","Runtime":"122 min","Genre":"Crime, Drama, Thriller","Director":"Todd Phillips","Writer":"Todd Phillips, Scott Silver, Bob Kane","Actors":"Joaquin Phoenix, Robert De Niro, Zazie Beetz","Plot":"The rise of Arthur Fleck, from aspiring stand-up comedian and pariah to Gotham's clown prince and leader of the revolution.","Language":"English","Country":"United States, Canada","Awards":"Won 2 Oscars. 122 wins & 239 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.4/10"},{"Source":"Rotten Tomatoes","Value":"69%"},{"Source":"Metacritic","Value":"59/100"}],"Metascore":"59","imdbRating":"8.4","imdbVotes":"1,341,316","imdbID":"tt7286456","Type":"movie","DVD":"03 Oct 2019","BoxOffice":"$335,477,657","Production":"N/A","Website":"N/A","Response":"True"}

const dictador = {"Title":"The Great Dictator","Year":"1940","Rated":"G","Released":"07 Mar 1941","Runtime":"125 min","Genre":"Comedy, Drama, War","Director":"Charles Chaplin","Writer":"Charles Chaplin","Actors":"Charles Chaplin, Paulette Goddard, Jack Oakie","Plot":"Dictator Adenoid Hynkel tries to expand his empire while a poor Jewish barber tries to avoid persecution from Hynkel's regime.","Language":"English, Esperanto, Latin","Country":"United States","Awards":"Nominated for 5 Oscars. 7 wins & 6 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMmExYWJjNTktNGUyZS00ODhmLTkxYzAtNWIzOGEyMGNiMmUwXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.4/10"},{"Source":"Rotten Tomatoes","Value":"92%"}],"Metascore":"N/A","imdbRating":"8.4","imdbVotes":"228,050","imdbID":"tt0032553","Type":"movie","DVD":"24 May 2011","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"}

const arca = {"Title":"Raiders of the Lost Ark","Year":"1981","Rated":"PG","Released":"12 Jun 1981","Runtime":"115 min","Genre":"Action, Adventure","Director":"Steven Spielberg","Writer":"Lawrence Kasdan, George Lucas, Philip Kaufman","Actors":"Harrison Ford, Karen Allen, Paul Freeman","Plot":"In 1936, archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before the Nazis can obtain its awesome powers.","Language":"English, German, Hebrew, Spanish, Arabic, Nepali","Country":"United States","Awards":"Won 4 Oscars. 38 wins & 24 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BNTU2ODkyY2MtMjU1NC00NjE1LWEzYjgtMWQ3MzRhMTE0NDc0XkEyXkFqcGdeQXVyMjM4MzQ4OTQ@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.4/10"},{"Source":"Rotten Tomatoes","Value":"93%"},{"Source":"Metacritic","Value":"85/100"}],"Metascore":"85","imdbRating":"8.4","imdbVotes":"983,111","imdbID":"tt0082971","Type":"movie","DVD":"13 May 2008","BoxOffice":"$248,159,971","Production":"N/A","Website":"N/A","Response":"True"}

const psicosis = {"Title":"Psycho","Year":"1960","Rated":"R","Released":"08 Sep 1960","Runtime":"109 min","Genre":"Horror, Mystery, Thriller","Director":"Alfred Hitchcock","Writer":"Joseph Stefano, Robert Bloch","Actors":"Anthony Perkins, Janet Leigh, Vera Miles","Plot":"A Phoenix secretary embezzles $40,000 from her employer's client, goes on the run and checks into a remote motel run by a young man under the domination of his mother.","Language":"English","Country":"United States","Awards":"Nominated for 4 Oscars. 7 wins & 14 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BNTQwNDM1YzItNDAxZC00NWY2LTk0M2UtNDIwNWI5OGUyNWUxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"96%"},{"Source":"Metacritic","Value":"97/100"}],"Metascore":"97","imdbRating":"8.5","imdbVotes":"685,440","imdbID":"tt0054215","Type":"movie","DVD":"04 Oct 2005","BoxOffice":"$32,000,000","Production":"N/A","Website":"N/A","Response":"True"}

const seven = {"Title":"Se7en","Year":"1995","Rated":"R","Released":"22 Sep 1995","Runtime":"127 min","Genre":"Crime, Drama, Mystery","Director":"David Fincher","Writer":"Andrew Kevin Walker","Actors":"Morgan Freeman, Brad Pitt, Kevin Spacey","Plot":"Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.","Language":"English","Country":"United States","Awards":"Nominated for 1 Oscar. 29 wins & 43 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.6/10"},{"Source":"Rotten Tomatoes","Value":"82%"},{"Source":"Metacritic","Value":"65/100"}],"Metascore":"65","imdbRating":"8.6","imdbVotes":"1,688,249","imdbID":"tt0114369","Type":"movie","DVD":"19 Dec 2000","BoxOffice":"$100,125,643","Production":"N/A","Website":"N/A","Response":"True"}


const array = [begin, casablanca, tesis, avatar, apartamento, faldas, guerraGalax, regreso, twoMuch, vivir, sobrevivire, hortelano, nombre, diasFutbol, tiemposModernos, pulp, vidaBella, sinPerdon, silencio, blade, roqueiii, amanece, terminator, inter, laJungla, diaBestia, odisea, brave, joker, dictador, arca, psicosis, seven];
var x = null;
let verPeli = null;
function calcPeli() {
    x = Math.floor(Math.random() * 33);
    verPeli= array[x];
    return verPeli;
}

function cambiarPelicula() {
    calcPeli();

    document.getElementById("title").textContent = "Título: " + verPeli.Title;
    document.getElementById("anyo").innerHTML = "Año: " + verPeli.Year;
    document.getElementById("director").textContent = "Director: " + verPeli.Director;
    document.getElementById("genre").textContent = "Género: " + verPeli.Genre;
    document.getElementById("runtime").textContent = "Duración: " + verPeli.Runtime;
    document.getElementById("actors").textContent = "Actrices/Actores: " + verPeli.Actors;
    document.querySelector("#img").src = verPeli.Poster + "alt='Poster de la película'";
}
